services:
  broker:
    build:
      context: ./go-broker
    image: driftpursuit/broker:latest
    environment:
      BROKER_ADDR: 0.0.0.0:43127
      BROKER_LOG_LEVEL: info
      # If you're not using gRPC from other services, disable it to avoid secret errors:
      BROKER_GRPC_AUTH_MODE: shared_secret
      BROKER_GRPC_SHARED_SECRET: local-development-shared-secret
    ports:
      - "43127:43127"
    networks:
      - battleground
    restart: unless-stopped

  bot-runner:
    build:
      context: ./python-sim
    image: driftpursuit/bot-runner:latest
    depends_on:
      - broker
    environment:
      BROKER_WS_URL: ws://broker:43127/ws   # container-to-container DNS works
      TRACE_HEADER: X-Trace-ID
      WEB_BRIDGE_HOST: 0.0.0.0
      WEB_BRIDGE_PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - battleground
    restart: unless-stopped

  game:
    build:
      context: .
      dockerfile: game/Dockerfile
      args:
        NEXT_PUBLIC_BROKER_WS_URL: ws://broker:43127/ws
        NEXT_PUBLIC_BROKER_HTTP_URL: http://broker:43127
    image: driftpursuit/game:latest
    depends_on:
      - broker
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BROKER_WS_URL: ws://broker:43127/ws
      NEXT_PUBLIC_BROKER_HTTP_URL: http://broker:43127
    ports:
      - "3000:3000"
    networks:
      - battleground
    restart: unless-stopped

networks:
  battleground:
    driver: bridge
