# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go-broker/internal/proto/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%go-broker/internal/proto/events.proto\x12\x1a\x64riftpursuit.networking.v1\"\xb1\x02\n\tGameEvent\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x16\n\x0eoccurred_at_ms\x18\x03 \x01(\x03\x12\x33\n\x04type\x18\x04 \x01(\x0e\x32%.driftpursuit.networking.v1.EventType\x12\x19\n\x11primary_entity_id\x18\x05 \x01(\t\x12\x1a\n\x12related_entity_ids\x18\x06 \x03(\t\x12\x45\n\x08metadata\x18\x07 \x03(\x0b\x32\x33.driftpursuit.networking.v1.GameEvent.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xd2\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x45VENT_TYPE_SPAWNED\x10\x01\x12\x18\n\x14\x45VENT_TYPE_DESTROYED\x10\x02\x12\x18\n\x14\x45VENT_TYPE_COLLISION\x10\x03\x12!\n\x1d\x45VENT_TYPE_OBJECTIVE_CAPTURED\x10\x04\x12\x1b\n\x17\x45VENT_TYPE_SCORE_UPDATE\x10\x05\x12\x1d\n\x19\x45VENT_TYPE_SENSOR_CONTACT\x10\x06\x42R\n$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'go_broker.internal.proto.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$build.buf.driftpursuit.networking.v1P\001Z(driftpursuit/broker/internal/proto/pb;pb'
  _GAMEEVENT_METADATAENTRY._options = None
  _GAMEEVENT_METADATAENTRY._serialized_options = b'8\001'
  _EVENTTYPE._serialized_start=378
  _EVENTTYPE._serialized_end=588
  _GAMEEVENT._serialized_start=70
  _GAMEEVENT._serialized_end=375
  _GAMEEVENT_METADATAENTRY._serialized_start=328
  _GAMEEVENT_METADATAENTRY._serialized_end=375
# @@protoc_insertion_point(module_scope)
