# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go-broker/internal/proto/radar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from go_broker.internal.proto import types_pb2 as go__broker_dot_internal_dot_proto_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$go-broker/internal/proto/radar.proto\x12\x1a\x64riftpursuit.networking.v1\x1a$go-broker/internal/proto/types.proto\"\xa5\x01\n\nRadarFrame\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\x19\n\x11\x65mitter_entity_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63\x61ptured_at_ms\x18\x04 \x01(\x03\x12:\n\x08\x63ontacts\x18\x05 \x03(\x0b\x32(.driftpursuit.networking.v1.RadarContact\"\xfb\x01\n\x0cRadarContact\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12\x10\n\x08track_id\x18\x02 \x01(\t\x12\x11\n\tentity_id\x18\x03 \x01(\t\x12\x0f\n\x07range_m\x18\x04 \x01(\x01\x12\x13\n\x0b\x62\x65\x61ring_deg\x18\x05 \x01(\x01\x12\x15\n\relevation_deg\x18\x06 \x01(\x01\x12\x1b\n\x13radial_velocity_mps\x18\x07 \x01(\x01\x12\x12\n\nconfidence\x18\x08 \x01(\x01\x12@\n\x0esuggested_tier\x18\t \x01(\x0e\x32(.driftpursuit.networking.v1.InterestTierBR\n$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'go_broker.internal.proto.radar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$build.buf.driftpursuit.networking.v1P\001Z(driftpursuit/broker/internal/proto/pb;pb'
  _RADARFRAME._serialized_start=107
  _RADARFRAME._serialized_end=272
  _RADARCONTACT._serialized_start=275
  _RADARCONTACT._serialized_end=526
# @@protoc_insertion_point(module_scope)
