# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go-broker/internal/proto/types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$go-broker/internal/proto/types.proto\x12\x1a\x64riftpursuit.networking.v1\"<\n\rSchemaVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\r\n\x05patch\x18\x03 \x01(\r\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"C\n\x0bOrientation\x12\x0f\n\x07yaw_deg\x18\x01 \x01(\x01\x12\x11\n\tpitch_deg\x18\x02 \x01(\x01\x12\x10\n\x08roll_deg\x18\x03 \x01(\x01*\xaf\x01\n\x0cInterestTier\x12\x1d\n\x19INTEREST_TIER_UNSPECIFIED\x10\x00\x12\x16\n\x12INTEREST_TIER_SELF\x10\x01\x12\x18\n\x14INTEREST_TIER_NEARBY\x10\x02\x12\x17\n\x13INTEREST_TIER_RADAR\x10\x03\x12\x1a\n\x16INTEREST_TIER_EXTENDED\x10\x04\x12\x19\n\x15INTEREST_TIER_PASSIVE\x10\x05\x42R\n$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'go_broker.internal.proto.types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$build.buf.driftpursuit.networking.v1P\001Z(driftpursuit/broker/internal/proto/pb;pb'
  _INTERESTTIER._serialized_start=244
  _INTERESTTIER._serialized_end=419
  _SCHEMAVERSION._serialized_start=68
  _SCHEMAVERSION._serialized_end=128
  _VECTOR3._serialized_start=130
  _VECTOR3._serialized_end=172
  _ORIENTATION._serialized_start=174
  _ORIENTATION._serialized_end=241
# @@protoc_insertion_point(module_scope)
