// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: go-broker/internal/proto/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED        EventType = 0
	EventType_EVENT_TYPE_SPAWNED            EventType = 1
	EventType_EVENT_TYPE_DESTROYED          EventType = 2
	EventType_EVENT_TYPE_COLLISION          EventType = 3
	EventType_EVENT_TYPE_OBJECTIVE_CAPTURED EventType = 4
	EventType_EVENT_TYPE_SCORE_UPDATE       EventType = 5
	EventType_EVENT_TYPE_SENSOR_CONTACT     EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_SPAWNED",
		2: "EVENT_TYPE_DESTROYED",
		3: "EVENT_TYPE_COLLISION",
		4: "EVENT_TYPE_OBJECTIVE_CAPTURED",
		5: "EVENT_TYPE_SCORE_UPDATE",
		6: "EVENT_TYPE_SENSOR_CONTACT",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":        0,
		"EVENT_TYPE_SPAWNED":            1,
		"EVENT_TYPE_DESTROYED":          2,
		"EVENT_TYPE_COLLISION":          3,
		"EVENT_TYPE_OBJECTIVE_CAPTURED": 4,
		"EVENT_TYPE_SCORE_UPDATE":       5,
		"EVENT_TYPE_SENSOR_CONTACT":     6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_go_broker_internal_proto_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_go_broker_internal_proto_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_events_proto_rawDescGZIP(), []int{0}
}

// Event stream emitted alongside snapshots describing discrete gameplay updates.
type GameEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAtMs     int64                  `protobuf:"varint,3,opt,name=occurred_at_ms,json=occurredAtMs,proto3" json:"occurred_at_ms,omitempty"`
	Type             EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=driftpursuit.networking.v1.EventType" json:"type,omitempty"`
	PrimaryEntityId  string                 `protobuf:"bytes,5,opt,name=primary_entity_id,json=primaryEntityId,proto3" json:"primary_entity_id,omitempty"`
	RelatedEntityIds []string               `protobuf:"bytes,6,rep,name=related_entity_ids,json=relatedEntityIds,proto3" json:"related_entity_ids,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_go_broker_internal_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *GameEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GameEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GameEvent) GetOccurredAtMs() int64 {
	if x != nil {
		return x.OccurredAtMs
	}
	return 0
}

func (x *GameEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *GameEvent) GetPrimaryEntityId() string {
	if x != nil {
		return x.PrimaryEntityId
	}
	return ""
}

func (x *GameEvent) GetRelatedEntityIds() []string {
	if x != nil {
		return x.RelatedEntityIds
	}
	return nil
}

func (x *GameEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_go_broker_internal_proto_events_proto protoreflect.FileDescriptor

const file_go_broker_internal_proto_events_proto_rawDesc = "" +
	"\n" +
	"%go-broker/internal/proto/events.proto\x12\x1adriftpursuit.networking.v1\"\x96\x03\n" +
	"\tGameEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12$\n" +
	"\x0eoccurred_at_ms\x18\x03 \x01(\x03R\foccurredAtMs\x129\n" +
	"\x04type\x18\x04 \x01(\x0e2%.driftpursuit.networking.v1.EventTypeR\x04type\x12*\n" +
	"\x11primary_entity_id\x18\x05 \x01(\tR\x0fprimaryEntityId\x12,\n" +
	"\x12related_entity_ids\x18\x06 \x03(\tR\x10relatedEntityIds\x12O\n" +
	"\bmetadata\x18\a \x03(\v23.driftpursuit.networking.v1.GameEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd2\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_SPAWNED\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_DESTROYED\x10\x02\x12\x18\n" +
	"\x14EVENT_TYPE_COLLISION\x10\x03\x12!\n" +
	"\x1dEVENT_TYPE_OBJECTIVE_CAPTURED\x10\x04\x12\x1b\n" +
	"\x17EVENT_TYPE_SCORE_UPDATE\x10\x05\x12\x1d\n" +
	"\x19EVENT_TYPE_SENSOR_CONTACT\x10\x06BR\n" +
	"$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3"

var (
	file_go_broker_internal_proto_events_proto_rawDescOnce sync.Once
	file_go_broker_internal_proto_events_proto_rawDescData []byte
)

func file_go_broker_internal_proto_events_proto_rawDescGZIP() []byte {
	file_go_broker_internal_proto_events_proto_rawDescOnce.Do(func() {
		file_go_broker_internal_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_broker_internal_proto_events_proto_rawDesc), len(file_go_broker_internal_proto_events_proto_rawDesc)))
	})
	return file_go_broker_internal_proto_events_proto_rawDescData
}

var file_go_broker_internal_proto_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_broker_internal_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_broker_internal_proto_events_proto_goTypes = []any{
	(EventType)(0),    // 0: driftpursuit.networking.v1.EventType
	(*GameEvent)(nil), // 1: driftpursuit.networking.v1.GameEvent
	nil,               // 2: driftpursuit.networking.v1.GameEvent.MetadataEntry
}
var file_go_broker_internal_proto_events_proto_depIdxs = []int32{
	0, // 0: driftpursuit.networking.v1.GameEvent.type:type_name -> driftpursuit.networking.v1.EventType
	2, // 1: driftpursuit.networking.v1.GameEvent.metadata:type_name -> driftpursuit.networking.v1.GameEvent.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_go_broker_internal_proto_events_proto_init() }
func file_go_broker_internal_proto_events_proto_init() {
	if File_go_broker_internal_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_broker_internal_proto_events_proto_rawDesc), len(file_go_broker_internal_proto_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_broker_internal_proto_events_proto_goTypes,
		DependencyIndexes: file_go_broker_internal_proto_events_proto_depIdxs,
		EnumInfos:         file_go_broker_internal_proto_events_proto_enumTypes,
		MessageInfos:      file_go_broker_internal_proto_events_proto_msgTypes,
	}.Build()
	File_go_broker_internal_proto_events_proto = out.File
	file_go_broker_internal_proto_events_proto_goTypes = nil
	file_go_broker_internal_proto_events_proto_depIdxs = nil
}
