// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: internal/proto/radar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RadarFrame carries processed sensor contacts for a single sweep.
type RadarFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion   string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	FrameId         uint64                 `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	EmitterEntityId string                 `protobuf:"bytes,3,opt,name=emitter_entity_id,json=emitterEntityId,proto3" json:"emitter_entity_id,omitempty"`
	CapturedAtMs    int64                  `protobuf:"varint,4,opt,name=captured_at_ms,json=capturedAtMs,proto3" json:"captured_at_ms,omitempty"`
	Contacts        []*RadarContact        `protobuf:"bytes,5,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RadarFrame) Reset() {
	*x = RadarFrame{}
	mi := &file_internal_proto_radar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarFrame) ProtoMessage() {}

func (x *RadarFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarFrame.ProtoReflect.Descriptor instead.
func (*RadarFrame) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{0}
}

func (x *RadarFrame) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RadarFrame) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RadarFrame) GetEmitterEntityId() string {
	if x != nil {
		return x.EmitterEntityId
	}
	return ""
}

func (x *RadarFrame) GetCapturedAtMs() int64 {
	if x != nil {
		return x.CapturedAtMs
	}
	return 0
}

func (x *RadarFrame) GetContacts() []*RadarContact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

// RadarContact bundles detections originating from a single sensor source.
type RadarContact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SourceEntityId string                 `protobuf:"bytes,2,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	Entries        []*RadarContactEntry   `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RadarContact) Reset() {
	*x = RadarContact{}
	mi := &file_internal_proto_radar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarContact) ProtoMessage() {}

func (x *RadarContact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarContact.ProtoReflect.Descriptor instead.
func (*RadarContact) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{1}
}

func (x *RadarContact) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RadarContact) GetSourceEntityId() string {
	if x != nil {
		return x.SourceEntityId
	}
	return ""
}

func (x *RadarContact) GetEntries() []*RadarContactEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RadarContactEntry captures the per-target solution produced by the radar.
type RadarContactEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetEntityId string                 `protobuf:"bytes,1,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	Position       *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity       *Vector3               `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Confidence     float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Occluded       bool                   `protobuf:"varint,5,opt,name=occluded,proto3" json:"occluded,omitempty"`
	SuggestedTier  InterestTier           `protobuf:"varint,6,opt,name=suggested_tier,json=suggestedTier,proto3,enum=driftpursuit.networking.v1.InterestTier" json:"suggested_tier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RadarContactEntry) Reset() {
	*x = RadarContactEntry{}
	mi := &file_internal_proto_radar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarContactEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarContactEntry) ProtoMessage() {}

func (x *RadarContactEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarContactEntry.ProtoReflect.Descriptor instead.
func (*RadarContactEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{2}
}

func (x *RadarContactEntry) GetTargetEntityId() string {
	if x != nil {
		return x.TargetEntityId
	}
	return ""
}

func (x *RadarContactEntry) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RadarContactEntry) GetVelocity() *Vector3 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *RadarContactEntry) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RadarContactEntry) GetOccluded() bool {
	if x != nil {
		return x.Occluded
	}
	return false
}

func (x *RadarContactEntry) GetSuggestedTier() InterestTier {
	if x != nil {
		return x.SuggestedTier
	}
	return InterestTier_INTEREST_TIER_UNSPECIFIED
}

var File_internal_proto_radar_proto protoreflect.FileDescriptor

const file_internal_proto_radar_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/radar.proto\x12\x1adriftpursuit.networking.v1\x1a$go-broker/internal/proto/types.proto\"\xe6\x01\n" +
	"\n" +
	"RadarFrame\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x04R\aframeId\x12*\n" +
	"\x11emitter_entity_id\x18\x03 \x01(\tR\x0femitterEntityId\x12$\n" +
	"\x0ecaptured_at_ms\x18\x04 \x01(\x03R\fcapturedAtMs\x12D\n" +
	"\bcontacts\x18\x05 \x03(\v2(.driftpursuit.networking.v1.RadarContactR\bcontacts\"\xa8\x01\n" +
	"\fRadarContact\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12(\n" +
	"\x10source_entity_id\x18\x02 \x01(\tR\x0esourceEntityId\x12G\n" +
	"\aentries\x18\x03 \x03(\v2-.driftpursuit.networking.v1.RadarContactEntryR\aentries\"\xcc\x02\n" +
	"\x11RadarContactEntry\x12(\n" +
	"\x10target_entity_id\x18\x01 \x01(\tR\x0etargetEntityId\x12?\n" +
	"\bposition\x18\x02 \x01(\v2#.driftpursuit.networking.v1.Vector3R\bposition\x12?\n" +
	"\bvelocity\x18\x03 \x01(\v2#.driftpursuit.networking.v1.Vector3R\bvelocity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\boccluded\x18\x05 \x01(\bR\boccluded\x12O\n" +
	"\x0esuggested_tier\x18\x06 \x01(\x0e2(.driftpursuit.networking.v1.InterestTierR\rsuggestedTierBR\n" +
	"$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3"

var (
	file_internal_proto_radar_proto_rawDescOnce sync.Once
	file_internal_proto_radar_proto_rawDescData []byte
)

func file_internal_proto_radar_proto_rawDescGZIP() []byte {
	file_internal_proto_radar_proto_rawDescOnce.Do(func() {
		file_internal_proto_radar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_radar_proto_rawDesc), len(file_internal_proto_radar_proto_rawDesc)))
	})
	return file_internal_proto_radar_proto_rawDescData
}

var file_internal_proto_radar_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_radar_proto_goTypes = []any{
	(*RadarFrame)(nil),        // 0: driftpursuit.networking.v1.RadarFrame
	(*RadarContact)(nil),      // 1: driftpursuit.networking.v1.RadarContact
	(*RadarContactEntry)(nil), // 2: driftpursuit.networking.v1.RadarContactEntry
	(*Vector3)(nil),           // 3: driftpursuit.networking.v1.Vector3
	(InterestTier)(0),         // 4: driftpursuit.networking.v1.InterestTier
}
var file_internal_proto_radar_proto_depIdxs = []int32{
	1, // 0: driftpursuit.networking.v1.RadarFrame.contacts:type_name -> driftpursuit.networking.v1.RadarContact
	2, // 1: driftpursuit.networking.v1.RadarContact.entries:type_name -> driftpursuit.networking.v1.RadarContactEntry
	3, // 2: driftpursuit.networking.v1.RadarContactEntry.position:type_name -> driftpursuit.networking.v1.Vector3
	3, // 3: driftpursuit.networking.v1.RadarContactEntry.velocity:type_name -> driftpursuit.networking.v1.Vector3
	4, // 4: driftpursuit.networking.v1.RadarContactEntry.suggested_tier:type_name -> driftpursuit.networking.v1.InterestTier
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_radar_proto_init() }
func file_internal_proto_radar_proto_init() {
	if File_internal_proto_radar_proto != nil {
		return
	}
	file_go_broker_internal_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_radar_proto_rawDesc), len(file_internal_proto_radar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_radar_proto_goTypes,
		DependencyIndexes: file_internal_proto_radar_proto_depIdxs,
		MessageInfos:      file_internal_proto_radar_proto_msgTypes,
	}.Build()
	File_internal_proto_radar_proto = out.File
	file_internal_proto_radar_proto_goTypes = nil
	file_internal_proto_radar_proto_depIdxs = nil
}
