// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: go-broker/internal/proto/snapshots.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snapshot of an entity's physical state that is broadcast to clients.
type EntitySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Position      *Vector3               `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vector3               `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Orientation   *Orientation           `protobuf:"bytes,6,opt,name=orientation,proto3" json:"orientation,omitempty"`
	SpeedMps      float64                `protobuf:"fixed64,7,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	// Optional radar cross section in square meters. Zero implies unknown.
	RadarCrossSection float64 `protobuf:"fixed64,9,opt,name=radar_cross_section,json=radarCrossSection,proto3" json:"radar_cross_section,omitempty"`
	CapturedAtMs      int64   `protobuf:"varint,10,opt,name=captured_at_ms,json=capturedAtMs,proto3" json:"captured_at_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EntitySnapshot) Reset() {
	*x = EntitySnapshot{}
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySnapshot) ProtoMessage() {}

func (x *EntitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySnapshot.ProtoReflect.Descriptor instead.
func (*EntitySnapshot) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *EntitySnapshot) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EntitySnapshot) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntitySnapshot) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntitySnapshot) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntitySnapshot) GetVelocity() *Vector3 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntitySnapshot) GetOrientation() *Orientation {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *EntitySnapshot) GetSpeedMps() float64 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *EntitySnapshot) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *EntitySnapshot) GetRadarCrossSection() float64 {
	if x != nil {
		return x.RadarCrossSection
	}
	return 0
}

func (x *EntitySnapshot) GetCapturedAtMs() int64 {
	if x != nil {
		return x.CapturedAtMs
	}
	return 0
}

// Aggregated world state replayed on connect and after broker restarts.
type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CapturedAtMs  int64                  `protobuf:"varint,2,opt,name=captured_at_ms,json=capturedAtMs,proto3" json:"captured_at_ms,omitempty"`
	Entities      []*EntitySnapshot      `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	Assignments   []*TierAssignment      `protobuf:"bytes,4,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *WorldSnapshot) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *WorldSnapshot) GetCapturedAtMs() int64 {
	if x != nil {
		return x.CapturedAtMs
	}
	return 0
}

func (x *WorldSnapshot) GetEntities() []*EntitySnapshot {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *WorldSnapshot) GetAssignments() []*TierAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

// Observer state communicated by gameplay clients to seed tier calculations.
type ObserverState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ObserverId    string                 `protobuf:"bytes,2,opt,name=observer_id,json=observerId,proto3" json:"observer_id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Orientation   *Orientation           `protobuf:"bytes,4,opt,name=orientation,proto3" json:"orientation,omitempty"`
	NearbyRangeM  float64                `protobuf:"fixed64,5,opt,name=nearby_range_m,json=nearbyRangeM,proto3" json:"nearby_range_m,omitempty"`
	RadarRangeM   float64                `protobuf:"fixed64,6,opt,name=radar_range_m,json=radarRangeM,proto3" json:"radar_range_m,omitempty"`
	UpdatedAtMs   int64                  `protobuf:"varint,7,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverState) Reset() {
	*x = ObserverState{}
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverState) ProtoMessage() {}

func (x *ObserverState) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverState.ProtoReflect.Descriptor instead.
func (*ObserverState) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *ObserverState) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ObserverState) GetObserverId() string {
	if x != nil {
		return x.ObserverId
	}
	return ""
}

func (x *ObserverState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ObserverState) GetOrientation() *Orientation {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *ObserverState) GetNearbyRangeM() float64 {
	if x != nil {
		return x.NearbyRangeM
	}
	return 0
}

func (x *ObserverState) GetRadarRangeM() float64 {
	if x != nil {
		return x.RadarRangeM
	}
	return 0
}

func (x *ObserverState) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

// Pre-computed tier assignment for a particular observer/entity pair.
type TierAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ObserverId    string                 `protobuf:"bytes,2,opt,name=observer_id,json=observerId,proto3" json:"observer_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Tier          InterestTier           `protobuf:"varint,4,opt,name=tier,proto3,enum=driftpursuit.networking.v1.InterestTier" json:"tier,omitempty"`
	ComputedAtMs  int64                  `protobuf:"varint,5,opt,name=computed_at_ms,json=computedAtMs,proto3" json:"computed_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierAssignment) Reset() {
	*x = TierAssignment{}
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierAssignment) ProtoMessage() {}

func (x *TierAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierAssignment.ProtoReflect.Descriptor instead.
func (*TierAssignment) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_snapshots_proto_rawDescGZIP(), []int{3}
}

func (x *TierAssignment) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TierAssignment) GetObserverId() string {
	if x != nil {
		return x.ObserverId
	}
	return ""
}

func (x *TierAssignment) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *TierAssignment) GetTier() InterestTier {
	if x != nil {
		return x.Tier
	}
	return InterestTier_INTEREST_TIER_UNSPECIFIED
}

func (x *TierAssignment) GetComputedAtMs() int64 {
	if x != nil {
		return x.ComputedAtMs
	}
	return 0
}

var File_go_broker_internal_proto_snapshots_proto protoreflect.FileDescriptor

const file_go_broker_internal_proto_snapshots_proto_rawDesc = "" +
	"\n" +
	"(go-broker/internal/proto/snapshots.proto\x12\x1adriftpursuit.networking.v1\x1a$go-broker/internal/proto/types.proto\"\xcd\x03\n" +
	"\x0eEntitySnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12?\n" +
	"\bposition\x18\x04 \x01(\v2#.driftpursuit.networking.v1.Vector3R\bposition\x12?\n" +
	"\bvelocity\x18\x05 \x01(\v2#.driftpursuit.networking.v1.Vector3R\bvelocity\x12I\n" +
	"\vorientation\x18\x06 \x01(\v2'.driftpursuit.networking.v1.OrientationR\vorientation\x12\x1b\n" +
	"\tspeed_mps\x18\a \x01(\x01R\bspeedMps\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12.\n" +
	"\x13radar_cross_section\x18\t \x01(\x01R\x11radarCrossSection\x12$\n" +
	"\x0ecaptured_at_ms\x18\n" +
	" \x01(\x03R\fcapturedAtMs\"\xf2\x01\n" +
	"\rWorldSnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12$\n" +
	"\x0ecaptured_at_ms\x18\x02 \x01(\x03R\fcapturedAtMs\x12F\n" +
	"\bentities\x18\x03 \x03(\v2*.driftpursuit.networking.v1.EntitySnapshotR\bentities\x12L\n" +
	"\vassignments\x18\x04 \x03(\v2*.driftpursuit.networking.v1.TierAssignmentR\vassignments\"\xd1\x02\n" +
	"\rObserverState\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vobserver_id\x18\x02 \x01(\tR\n" +
	"observerId\x12?\n" +
	"\bposition\x18\x03 \x01(\v2#.driftpursuit.networking.v1.Vector3R\bposition\x12I\n" +
	"\vorientation\x18\x04 \x01(\v2'.driftpursuit.networking.v1.OrientationR\vorientation\x12$\n" +
	"\x0enearby_range_m\x18\x05 \x01(\x01R\fnearbyRangeM\x12\"\n" +
	"\rradar_range_m\x18\x06 \x01(\x01R\vradarRangeM\x12\"\n" +
	"\rupdated_at_ms\x18\a \x01(\x03R\vupdatedAtMs\"\xd9\x01\n" +
	"\x0eTierAssignment\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vobserver_id\x18\x02 \x01(\tR\n" +
	"observerId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12<\n" +
	"\x04tier\x18\x04 \x01(\x0e2(.driftpursuit.networking.v1.InterestTierR\x04tier\x12$\n" +
	"\x0ecomputed_at_ms\x18\x05 \x01(\x03R\fcomputedAtMsBR\n" +
	"$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3"

var (
	file_go_broker_internal_proto_snapshots_proto_rawDescOnce sync.Once
	file_go_broker_internal_proto_snapshots_proto_rawDescData []byte
)

func file_go_broker_internal_proto_snapshots_proto_rawDescGZIP() []byte {
	file_go_broker_internal_proto_snapshots_proto_rawDescOnce.Do(func() {
		file_go_broker_internal_proto_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_broker_internal_proto_snapshots_proto_rawDesc), len(file_go_broker_internal_proto_snapshots_proto_rawDesc)))
	})
	return file_go_broker_internal_proto_snapshots_proto_rawDescData
}

var file_go_broker_internal_proto_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_go_broker_internal_proto_snapshots_proto_goTypes = []any{
	(*EntitySnapshot)(nil), // 0: driftpursuit.networking.v1.EntitySnapshot
	(*WorldSnapshot)(nil),  // 1: driftpursuit.networking.v1.WorldSnapshot
	(*ObserverState)(nil),  // 2: driftpursuit.networking.v1.ObserverState
	(*TierAssignment)(nil), // 3: driftpursuit.networking.v1.TierAssignment
	(*Vector3)(nil),        // 4: driftpursuit.networking.v1.Vector3
	(*Orientation)(nil),    // 5: driftpursuit.networking.v1.Orientation
	(InterestTier)(0),      // 6: driftpursuit.networking.v1.InterestTier
}
var file_go_broker_internal_proto_snapshots_proto_depIdxs = []int32{
	4, // 0: driftpursuit.networking.v1.EntitySnapshot.position:type_name -> driftpursuit.networking.v1.Vector3
	4, // 1: driftpursuit.networking.v1.EntitySnapshot.velocity:type_name -> driftpursuit.networking.v1.Vector3
	5, // 2: driftpursuit.networking.v1.EntitySnapshot.orientation:type_name -> driftpursuit.networking.v1.Orientation
	0, // 3: driftpursuit.networking.v1.WorldSnapshot.entities:type_name -> driftpursuit.networking.v1.EntitySnapshot
	3, // 4: driftpursuit.networking.v1.WorldSnapshot.assignments:type_name -> driftpursuit.networking.v1.TierAssignment
	4, // 5: driftpursuit.networking.v1.ObserverState.position:type_name -> driftpursuit.networking.v1.Vector3
	5, // 6: driftpursuit.networking.v1.ObserverState.orientation:type_name -> driftpursuit.networking.v1.Orientation
	6, // 7: driftpursuit.networking.v1.TierAssignment.tier:type_name -> driftpursuit.networking.v1.InterestTier
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_go_broker_internal_proto_snapshots_proto_init() }
func file_go_broker_internal_proto_snapshots_proto_init() {
	if File_go_broker_internal_proto_snapshots_proto != nil {
		return
	}
	file_go_broker_internal_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_broker_internal_proto_snapshots_proto_rawDesc), len(file_go_broker_internal_proto_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_broker_internal_proto_snapshots_proto_goTypes,
		DependencyIndexes: file_go_broker_internal_proto_snapshots_proto_depIdxs,
		MessageInfos:      file_go_broker_internal_proto_snapshots_proto_msgTypes,
	}.Build()
	File_go_broker_internal_proto_snapshots_proto = out.File
	file_go_broker_internal_proto_snapshots_proto_goTypes = nil
	file_go_broker_internal_proto_snapshots_proto_depIdxs = nil
}
