// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/driftpursuit/broker/v0/time_sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_proto_driftpursuit_broker_v0_time_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driftpursuit_broker_v0_time_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSyncRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TimeSyncUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestampMs    int64                  `protobuf:"varint,1,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`
	SimulatedTimestampMs int64                  `protobuf:"varint,2,opt,name=simulated_timestamp_ms,json=simulatedTimestampMs,proto3" json:"simulated_timestamp_ms,omitempty"`
	RecommendedOffsetMs  int64                  `protobuf:"varint,3,opt,name=recommended_offset_ms,json=recommendedOffsetMs,proto3" json:"recommended_offset_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TimeSyncUpdate) Reset() {
	*x = TimeSyncUpdate{}
	mi := &file_proto_driftpursuit_broker_v0_time_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncUpdate) ProtoMessage() {}

func (x *TimeSyncUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driftpursuit_broker_v0_time_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncUpdate.ProtoReflect.Descriptor instead.
func (*TimeSyncUpdate) Descriptor() ([]byte, []int) {
	return file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSyncUpdate) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *TimeSyncUpdate) GetSimulatedTimestampMs() int64 {
	if x != nil {
		return x.SimulatedTimestampMs
	}
	return 0
}

func (x *TimeSyncUpdate) GetRecommendedOffsetMs() int64 {
	if x != nil {
		return x.RecommendedOffsetMs
	}
	return 0
}

var File_proto_driftpursuit_broker_v0_time_sync_proto protoreflect.FileDescriptor

const file_proto_driftpursuit_broker_v0_time_sync_proto_rawDesc = "" +
	"\n" +
	",proto/driftpursuit/broker/v0/time_sync.proto\x12\x16driftpursuit.broker.v0\".\n" +
	"\x0fTimeSyncRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xaa\x01\n" +
	"\x0eTimeSyncUpdate\x12.\n" +
	"\x13server_timestamp_ms\x18\x01 \x01(\x03R\x11serverTimestampMs\x124\n" +
	"\x16simulated_timestamp_ms\x18\x02 \x01(\x03R\x14simulatedTimestampMs\x122\n" +
	"\x15recommended_offset_ms\x18\x03 \x01(\x03R\x13recommendedOffsetMs2v\n" +
	"\x0fTimeSyncService\x12c\n" +
	"\x0eStreamTimeSync\x12'.driftpursuit.broker.v0.TimeSyncRequest\x1a&.driftpursuit.broker.v0.TimeSyncUpdate0\x01B'Z%driftpursuit/broker/internal/proto/pbb\x06proto3"

var (
	file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescOnce sync.Once
	file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescData []byte
)

func file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescGZIP() []byte {
	file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescOnce.Do(func() {
		file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driftpursuit_broker_v0_time_sync_proto_rawDesc), len(file_proto_driftpursuit_broker_v0_time_sync_proto_rawDesc)))
	})
	return file_proto_driftpursuit_broker_v0_time_sync_proto_rawDescData
}

var file_proto_driftpursuit_broker_v0_time_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_driftpursuit_broker_v0_time_sync_proto_goTypes = []any{
	(*TimeSyncRequest)(nil), // 0: driftpursuit.broker.v0.TimeSyncRequest
	(*TimeSyncUpdate)(nil),  // 1: driftpursuit.broker.v0.TimeSyncUpdate
}
var file_proto_driftpursuit_broker_v0_time_sync_proto_depIdxs = []int32{
	0, // 0: driftpursuit.broker.v0.TimeSyncService.StreamTimeSync:input_type -> driftpursuit.broker.v0.TimeSyncRequest
	1, // 1: driftpursuit.broker.v0.TimeSyncService.StreamTimeSync:output_type -> driftpursuit.broker.v0.TimeSyncUpdate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_driftpursuit_broker_v0_time_sync_proto_init() }
func file_proto_driftpursuit_broker_v0_time_sync_proto_init() {
	if File_proto_driftpursuit_broker_v0_time_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driftpursuit_broker_v0_time_sync_proto_rawDesc), len(file_proto_driftpursuit_broker_v0_time_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driftpursuit_broker_v0_time_sync_proto_goTypes,
		DependencyIndexes: file_proto_driftpursuit_broker_v0_time_sync_proto_depIdxs,
		MessageInfos:      file_proto_driftpursuit_broker_v0_time_sync_proto_msgTypes,
	}.Build()
	File_proto_driftpursuit_broker_v0_time_sync_proto = out.File
	file_proto_driftpursuit_broker_v0_time_sync_proto_goTypes = nil
	file_proto_driftpursuit_broker_v0_time_sync_proto_depIdxs = nil
}
