// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: go-broker/internal/proto/types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical interest tiers used by the broker to bucket subscriptions.
type InterestTier int32

const (
	InterestTier_INTEREST_TIER_UNSPECIFIED InterestTier = 0
	// The observing entity itself; always delivered.
	InterestTier_INTEREST_TIER_SELF InterestTier = 1
	// Entities within the close range bubble receive the full state stream.
	InterestTier_INTEREST_TIER_NEARBY InterestTier = 2
	// Entities inside the observer's radar volume receive degraded updates.
	InterestTier_INTEREST_TIER_RADAR InterestTier = 3
	// Entities outside radar range but still relevant for global awareness.
	InterestTier_INTEREST_TIER_EXTENDED InterestTier = 4
	// Dormant or destroyed entities only appear in high level summaries.
	InterestTier_INTEREST_TIER_PASSIVE InterestTier = 5
)

// Enum value maps for InterestTier.
var (
	InterestTier_name = map[int32]string{
		0: "INTEREST_TIER_UNSPECIFIED",
		1: "INTEREST_TIER_SELF",
		2: "INTEREST_TIER_NEARBY",
		3: "INTEREST_TIER_RADAR",
		4: "INTEREST_TIER_EXTENDED",
		5: "INTEREST_TIER_PASSIVE",
	}
	InterestTier_value = map[string]int32{
		"INTEREST_TIER_UNSPECIFIED": 0,
		"INTEREST_TIER_SELF":        1,
		"INTEREST_TIER_NEARBY":      2,
		"INTEREST_TIER_RADAR":       3,
		"INTEREST_TIER_EXTENDED":    4,
		"INTEREST_TIER_PASSIVE":     5,
	}
)

func (x InterestTier) Enum() *InterestTier {
	p := new(InterestTier)
	*p = x
	return p
}

func (x InterestTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterestTier) Descriptor() protoreflect.EnumDescriptor {
	return file_go_broker_internal_proto_types_proto_enumTypes[0].Descriptor()
}

func (InterestTier) Type() protoreflect.EnumType {
	return &file_go_broker_internal_proto_types_proto_enumTypes[0]
}

func (x InterestTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterestTier.Descriptor instead.
func (InterestTier) EnumDescriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_types_proto_rawDescGZIP(), []int{0}
}

// Semantic version of the networking schema carried in every payload.
type SchemaVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         uint32                 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersion) Reset() {
	*x = SchemaVersion{}
	mi := &file_go_broker_internal_proto_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersion) ProtoMessage() {}

func (x *SchemaVersion) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersion.ProtoReflect.Descriptor instead.
func (*SchemaVersion) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SchemaVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *SchemaVersion) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

// 3D vector in meters, relative to the simulation origin.
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_go_broker_internal_proto_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Euler orientation in degrees following aerospace conventions.
type Orientation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YawDeg        float64                `protobuf:"fixed64,1,opt,name=yaw_deg,json=yawDeg,proto3" json:"yaw_deg,omitempty"`
	PitchDeg      float64                `protobuf:"fixed64,2,opt,name=pitch_deg,json=pitchDeg,proto3" json:"pitch_deg,omitempty"`
	RollDeg       float64                `protobuf:"fixed64,3,opt,name=roll_deg,json=rollDeg,proto3" json:"roll_deg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orientation) Reset() {
	*x = Orientation{}
	mi := &file_go_broker_internal_proto_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orientation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orientation) ProtoMessage() {}

func (x *Orientation) ProtoReflect() protoreflect.Message {
	mi := &file_go_broker_internal_proto_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orientation.ProtoReflect.Descriptor instead.
func (*Orientation) Descriptor() ([]byte, []int) {
	return file_go_broker_internal_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *Orientation) GetYawDeg() float64 {
	if x != nil {
		return x.YawDeg
	}
	return 0
}

func (x *Orientation) GetPitchDeg() float64 {
	if x != nil {
		return x.PitchDeg
	}
	return 0
}

func (x *Orientation) GetRollDeg() float64 {
	if x != nil {
		return x.RollDeg
	}
	return 0
}

var File_go_broker_internal_proto_types_proto protoreflect.FileDescriptor

const file_go_broker_internal_proto_types_proto_rawDesc = "" +
	"\n" +
	"$go-broker/internal/proto/types.proto\x12\x1adriftpursuit.networking.v1\"Q\n" +
	"\rSchemaVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"^\n" +
	"\vOrientation\x12\x17\n" +
	"\ayaw_deg\x18\x01 \x01(\x01R\x06yawDeg\x12\x1b\n" +
	"\tpitch_deg\x18\x02 \x01(\x01R\bpitchDeg\x12\x19\n" +
	"\broll_deg\x18\x03 \x01(\x01R\arollDeg*\xaf\x01\n" +
	"\fInterestTier\x12\x1d\n" +
	"\x19INTEREST_TIER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INTEREST_TIER_SELF\x10\x01\x12\x18\n" +
	"\x14INTEREST_TIER_NEARBY\x10\x02\x12\x17\n" +
	"\x13INTEREST_TIER_RADAR\x10\x03\x12\x1a\n" +
	"\x16INTEREST_TIER_EXTENDED\x10\x04\x12\x19\n" +
	"\x15INTEREST_TIER_PASSIVE\x10\x05BR\n" +
	"$build.buf.driftpursuit.networking.v1P\x01Z(driftpursuit/broker/internal/proto/pb;pbb\x06proto3"

var (
	file_go_broker_internal_proto_types_proto_rawDescOnce sync.Once
	file_go_broker_internal_proto_types_proto_rawDescData []byte
)

func file_go_broker_internal_proto_types_proto_rawDescGZIP() []byte {
	file_go_broker_internal_proto_types_proto_rawDescOnce.Do(func() {
		file_go_broker_internal_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_broker_internal_proto_types_proto_rawDesc), len(file_go_broker_internal_proto_types_proto_rawDesc)))
	})
	return file_go_broker_internal_proto_types_proto_rawDescData
}

var file_go_broker_internal_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_broker_internal_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_go_broker_internal_proto_types_proto_goTypes = []any{
	(InterestTier)(0),     // 0: driftpursuit.networking.v1.InterestTier
	(*SchemaVersion)(nil), // 1: driftpursuit.networking.v1.SchemaVersion
	(*Vector3)(nil),       // 2: driftpursuit.networking.v1.Vector3
	(*Orientation)(nil),   // 3: driftpursuit.networking.v1.Orientation
}
var file_go_broker_internal_proto_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_broker_internal_proto_types_proto_init() }
func file_go_broker_internal_proto_types_proto_init() {
	if File_go_broker_internal_proto_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_broker_internal_proto_types_proto_rawDesc), len(file_go_broker_internal_proto_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_broker_internal_proto_types_proto_goTypes,
		DependencyIndexes: file_go_broker_internal_proto_types_proto_depIdxs,
		EnumInfos:         file_go_broker_internal_proto_types_proto_enumTypes,
		MessageInfos:      file_go_broker_internal_proto_types_proto_msgTypes,
	}.Build()
	File_go_broker_internal_proto_types_proto = out.File
	file_go_broker_internal_proto_types_proto_goTypes = nil
	file_go_broker_internal_proto_types_proto_depIdxs = nil
}
