name: Docker images

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build broker image
        run: docker build -t driftpursuit/broker:ci go-broker

      - name: Build bot runner image
        run: docker build -t driftpursuit/bot-runner:ci python-sim

      - name: Build web client image
        run: docker build -t driftpursuit/web-client:ci tunnelcave_sandbox_web
